# Site
title:              ShillyAsh
bio:                'Lives and times of a family of Shilly Ashes'
description:        "A catalogue of books, comics & graphic novels, poetry, music and travel... all things we are deeply passionate about."
locale:             en_US
baseurl: "" # the subpath of your site, e.g. /blog
url: http://www.shillyash.com

# Comments
disqus_shortname:   shillyash

# Social
analytics-id:       "default"
twitter:            default
facebook:           default
instagram:          default
github:             default

# personal
location:           Bangalore, KA
phone:              310-5555-8172
email:              info@default.com # change this to your email to receive free emails for your contact submissions via Slapform.com

# Other
background_image:   /images/bg.jpg
# Tip: The color palette and other styles can be configured in /_sass/lib/_vars.scss
slapform_thankyou_page: /thank-you

# Jekyll
#permalink:          /blog/:title/
permalink:          pretty
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

collections:
  comics:
    output: true
    permalink: /comics/:title/
  panorama:
    output: true
    permalink: /panorama/:title/
  classical:
    output: true
    permalink: /classical/:title/
  books:
    label: Books
    output: true
    sort_by: date
    permalink: /books/:title/
  trips:
    output: true
    permalink: /trips/:title/
  posts:
    output: true
    permalink: /blog/:title/
  art:
    output: true
    permalink: /art/:title/
  selfhosted:
    output: true
    permalink: /selfhosted/:title/

defaults:
- scope:
    type: comics
  values:
    layout: page
    collabel: Comics
    colurl: /comics/
- scope:
    type: panorama
  values:
    layout: page
    collabel: Panorama
    colurl: /panorama
- scope:
    type: art
  values:
    layout: artist
    needpopup: true
    collabel: Appreciating Art
    colurl: /art/
- scope:
    type: classical
  values:
    needsortable: true
    collabel: Classical
    colurl: /classical/
- scope:
    type: books
  values:
    layout: post
    collabel: Books
    colurl: /books/
- scope:
    type: trips
  values:
    layout: post
    collabel: Travelogues
    colurl: /trips/
- scope:
    type: posts
  values:
    layout: post
    collabel: Blog
    colurl: /blog/
- scope:
    type: selfhosted
  values:
    layout: page
    collabel: Self-Hosted
    colurl: /selfhosted/

autopages:
  enabled: false
  collections:
    layouts:
      - 'autopage_collection.html'
    title: 'Posts in collection :coll'
    permalink: '/collection/:coll'
    silent: false
    slugify:
      mode: 'default'
      case: false

# Gems
plugins:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jekyll-toc

toc:
  min_level: 2
  max_level: 3

# Pagination Settings
pagination:
  enabled: true
  per_page: 10
  permalink: '/:num/'
  title: ':title | :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
 # extension: htm
 # indexpage: 'default'
  trail: 
    before: 2
    after: 2

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile, old]
